## SimpleRNN
#### 4개의 연속된 실수를 담은 시퀀스가 주어졌을 때 다음에 나올 실수를 예측하는 모델
#### 예를 들어 [0.0, 0.1, 0.2, 0.3]의 연속된 실수를 담은 시퀀스에 대해 다음에 나올 실수인 [0.4]를 예측 

In [1]:
import numpy as np
from tensorflow.keras.layers import SimpleRNN, Dense
from tensorflow.keras.models import Sequential

In [2]:
X = []
Y = [] 

for i in range(5):
    # [0, 1, 2, 3]형태의 정수 시퀀스를 만듭니다.
    lst = list(range(i, i+4))

    # 위에서 만든 시퀀스의 숫자들을 각각 10으로 나누어 저장합니다.
    # SimpleRNN에서는 각 timesteps에 숫자가 하나씩 들어가기 때문에 하나씩 분리해서 배열에 저장합니다.
    X.append(list(map(lambda c : [c/10], lst)))

    # 정답에 해당하는 값을 Y에 저장합니다.
    Y.append((i+4)/10)    
    
X = np.array(X)
Y = np.array(Y)

for i in range(len(X)):
    print(X[i], Y[i])

[[0. ]
 [0.1]
 [0.2]
 [0.3]] 0.4
[[0.1]
 [0.2]
 [0.3]
 [0.4]] 0.5
[[0.2]
 [0.3]
 [0.4]
 [0.5]] 0.6
[[0.3]
 [0.4]
 [0.5]
 [0.6]] 0.7
[[0.4]
 [0.5]
 [0.6]
 [0.7]] 0.8


In [3]:
model = Sequential([
    # input_shape=[4,1]에서 [4,1]은 각각 timesteps와 input_dim을 의미합니다.
    # timesteps = RNN이 입력에 대해 계산을 반복하는 횟수, input_dim = 입력 벡터의 크기
    SimpleRNN(units=10, return_sequences=False,input_shape=[4,1]),
    Dense(1)
])

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [4]:
model.compile(optimizer='adam', loss='mse')
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
simple_rnn (SimpleRNN)       (None, 10)                120       
_________________________________________________________________
dense (Dense)                (None, 1)                 11        
Total params: 131
Trainable params: 131
Non-trainable params: 0
_________________________________________________________________


In [5]:
model.fit(X, Y, epochs=100, verbose=0)

In [6]:
model.predict(X)

array([[0.3735518 ],
       [0.5195996 ],
       [0.63060665],
       [0.7101812 ],
       [0.76565564]], dtype=float32)

In [7]:
model.predict(np.array([[[-0.4], [-0.3], [-0.2], [-0.1]]])) # 기댓값: 0.

array([[-0.3311995]], dtype=float32)

In [8]:
model.predict(np.array([[[0.8], [0.9], [1.0], [1.1]]])) # 기댓값: 1.2

array([[0.8676131]], dtype=float32)